interface EtudiantSpecialiteSemestre{
    nbModuleNV ?:number,
    nbModuleTotal ?:number,
    nbModuleAReporter ?:number,
    EtdSpecSms_FlagMaj ?:boolean,
    EtdSpecSms_Moyenne ?:number|null,
    EtdSpecSms_Validation ?:boolean|null,
    EtdSpecSms_MoyPriseEnCompte ?:boolean,
    EtdSpecSms_Id ?:string,
    Fac_Id ?:string,
    Ann_Nom ?:string,
    ACD_EtudiantSpecialiteSemestreModuleVw ?:string,
};


export interface CursusParNiveauEntity{
    EtdSpecAnn_Id :string,
    EtdSpecAnn_FlagMaj ?:boolean,
    SpecAnn_Id ?:string,
    Ses_Id ?:string|null,
    Etd_Matricule ?:string,
    Pers_Photo ?:string,
    Pers_Nom ?:string,
    Pers_Prenom ?:string,
    Spec_Name ?:string,
    Prg_Nom ?:string,
    Prg_Code ?:string,
    Ann_Nom ?:string,
    Niv_Nom ?:string,
    Niv_Id ?:string,
    EtdSpecAnn_AutreModPaiement ?:string|null,
    DecJury_Id ?:string,
    DecJury_Nom ?:string,
    EtdSpecAnn_Moyenne ?:number|null,
    EtdAnnStatu_Id ?:string,
    FacExt_Id ?:string|null,
    Mtn_Id ?:string,
    Mtn_Nom ?:string,
    ModInsc_Id ?:string,
    EtdPrg_Id ?:string,
    EtdSpecAnn_QuitPaie ?:boolean,
    EtdSpecAnn_QuitBib ?:boolean,
    EtdSpecAnn_QuitLog ?:boolean,
    EtdSpecAnn_QuitRespons ?:boolean,
    EtdSpecAnn_DecsManuel ?:boolean,
    EtdSpecAnn_QuitControle ?:boolean,
    EtdSpecAnn_Remarque ?:string|null,
    EtdAnnStatu_Nom ?:string,
    progAdm ?:string,
    EtdtSpcAnn_TimeStamp ?:string|null,
    ACD_EtudiantSpecialiteSemestreVw ?:EtudiantSpecialiteSemestre|null,
    SesUserName ?:string
}